[package]
name = "dotenv_aegis"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "package"
path = "scripts/build_package.rs"

[dependencies]
aegis-lang = "0.2.1"
dotenvy = "0.15.7"
